<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <VisualStudioVersion Condition="'$(VisualStudioVersion)' == ''">10.0</VisualStudioVersion>
    <TargetFramework Condition="'$(VisualStudioVersion)' == ''">net40</TargetFramework>
    <TargetFramework Condition="'$(VisualStudioVersion)' == '10.0'">net40</TargetFramework>
    <TargetFramework Condition="'$(VisualStudioVersion)' == '17.0'">net472</TargetFramework>
    <TargetFramework Condition="'$(VisualStudioVersion)' == '18.0'">net472</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>Sut.HtmlTest</RootNamespace>
    <AssemblyName>Sut.HtmlTest</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <LangVersion>7.3</LangVersion>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <IsCodedUITest>True</IsCodedUITest>
    <TestProjectType>CodedUITest</TestProjectType>
  </PropertyGroup>
  <Import Project="..\..\Project.props" />
  <ItemGroup>
    <Reference Include="WindowsBase" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\..\CommonAssemblyInfo.cs">
      <Link>Properties\CommonAssemblyInfo.cs</Link>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\CUITe\CUITe.csproj" />
    <ProjectReference Include="..\TestHelpers\TestHelpers.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="DynamicBrowserWindowTitle.1.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="DynamicBrowserWindowTitle.2.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="DynamicBrowserWindowTitle.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="iframe.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="iframe_test.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="TestHtmlPage.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <Import Project="$(SolutionDir)\Targets\CodedUITests.targets" />
  <Import Project="$(SolutionDir)\Targets\MSTest.targets" />
  <Import Project="$(SolutionDir)\Targets\CUIT.targets" />
</Project>
