// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CUITe.IntegrationTests.NuGet
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class NuGetFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "NuGet", "In order to use CUITe\r\nAs a developer\r\nI want to be able to add the CUITe NuGet p" +
                    "ackage to my Coded UI test project", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "NuGet")))
            {
                CUITe.IntegrationTests.NuGet.NuGetFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void AddingTheCUITeNuGetPackageToACodedUITestProject(string description, string visualStudioVersion, string targetFrameworkVersion, string nuGetPackageId, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Adding the CUITe NuGet package to a Coded UI test project", exampleTags);
            this.ScenarioSetup(scenarioInfo);
            testRunner.Given(string.Format("the Visual Studio version {0}", visualStudioVersion), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
            testRunner.When(string.Format("a new Coded UI test project is created with platform {0}", targetFrameworkVersion), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
            testRunner.And(string.Format("the CUITe nuget package \"{0}\" is added to the project", nuGetPackageId), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
            testRunner.And("test methods are added to the project which use CUITe to test the sample applicat" +
                    "ion(s)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
            testRunner.Then("the project should build and its tests run successfully", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Adding the CUITe NuGet package to a Coded UI test project")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "NuGet")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Visual Studio 2010 and .NET Framework 4.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Description", "Visual Studio 2010 and .NET Framework 4.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:VisualStudioVersion", "2010")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:TargetFrameworkVersion", "4.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NuGetPackageId", "CUITe.VS2010")]
        public virtual void AddingTheCUITeNuGetPackageToACodedUITestProject_VisualStudio2010And_NETFramework4_0()
        {
            this.AddingTheCUITeNuGetPackageToACodedUITestProject("Visual Studio 2010 and .NET Framework 4.0", "2010", "4.0", "CUITe.VS2010", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Adding the CUITe NuGet package to a Coded UI test project")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "NuGet")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Visual Studio 2010 and Silverlight 5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Description", "Visual Studio 2010 and Silverlight 5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:VisualStudioVersion", "2010")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:TargetFrameworkVersion", "4.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NuGetPackageId", "CUITe.Silverlight.VS2010")]
        public virtual void AddingTheCUITeNuGetPackageToACodedUITestProject_VisualStudio2010AndSilverlight5()
        {
            this.AddingTheCUITeNuGetPackageToACodedUITestProject("Visual Studio 2010 and Silverlight 5", "2010", "4.0", "CUITe.Silverlight.VS2010", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Adding the CUITe NuGet package to a Coded UI test project")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "NuGet")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Visual Studio 2012 and .NET Framework 4")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Description", "Visual Studio 2012 and .NET Framework 4")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:VisualStudioVersion", "2012")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:TargetFrameworkVersion", "4.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NuGetPackageId", "CUITe.VS2012")]
        public virtual void AddingTheCUITeNuGetPackageToACodedUITestProject_VisualStudio2012And_NETFramework4()
        {
            this.AddingTheCUITeNuGetPackageToACodedUITestProject("Visual Studio 2012 and .NET Framework 4", "2012", "4.0", "CUITe.VS2012", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Adding the CUITe NuGet package to a Coded UI test project")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "NuGet")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Visual Studio 2012 and .NET Framework 4.5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Description", "Visual Studio 2012 and .NET Framework 4.5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:VisualStudioVersion", "2012")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:TargetFrameworkVersion", "4.5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NuGetPackageId", "CUITe.VS2012")]
        public virtual void AddingTheCUITeNuGetPackageToACodedUITestProject_VisualStudio2012And_NETFramework4_5()
        {
            this.AddingTheCUITeNuGetPackageToACodedUITestProject("Visual Studio 2012 and .NET Framework 4.5", "2012", "4.5", "CUITe.VS2012", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Adding the CUITe NuGet package to a Coded UI test project")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "NuGet")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Visual Studio 2012 and .NET Framework 4.5.1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Description", "Visual Studio 2012 and .NET Framework 4.5.1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:VisualStudioVersion", "2012")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:TargetFrameworkVersion", "4.5.1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NuGetPackageId", "CUITe.VS2012")]
        public virtual void AddingTheCUITeNuGetPackageToACodedUITestProject_VisualStudio2012And_NETFramework4_5_1()
        {
            this.AddingTheCUITeNuGetPackageToACodedUITestProject("Visual Studio 2012 and .NET Framework 4.5.1", "2012", "4.5.1", "CUITe.VS2012", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Adding the CUITe NuGet package to a Coded UI test project")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "NuGet")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Visual Studio 2012 and .NET Framework 4.5.2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Description", "Visual Studio 2012 and .NET Framework 4.5.2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:VisualStudioVersion", "2012")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:TargetFrameworkVersion", "4.5.2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NuGetPackageId", "CUITe.VS2012")]
        public virtual void AddingTheCUITeNuGetPackageToACodedUITestProject_VisualStudio2012And_NETFramework4_5_2()
        {
            this.AddingTheCUITeNuGetPackageToACodedUITestProject("Visual Studio 2012 and .NET Framework 4.5.2", "2012", "4.5.2", "CUITe.VS2012", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Adding the CUITe NuGet package to a Coded UI test project")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "NuGet")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Visual Studio 2012 and .NET Framework 4.6")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Description", "Visual Studio 2012 and .NET Framework 4.6")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:VisualStudioVersion", "2012")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:TargetFrameworkVersion", "4.6")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NuGetPackageId", "CUITe.VS2012")]
        public virtual void AddingTheCUITeNuGetPackageToACodedUITestProject_VisualStudio2012And_NETFramework4_6()
        {
            this.AddingTheCUITeNuGetPackageToACodedUITestProject("Visual Studio 2012 and .NET Framework 4.6", "2012", "4.6", "CUITe.VS2012", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Adding the CUITe NuGet package to a Coded UI test project")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "NuGet")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Visual Studio 2012 and .NET Framework 4 and Silverlight 5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Description", "Visual Studio 2012 and .NET Framework 4 and Silverlight 5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:VisualStudioVersion", "2012")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:TargetFrameworkVersion", "4.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NuGetPackageId", "CUITe.Silverlight.VS2012")]
        public virtual void AddingTheCUITeNuGetPackageToACodedUITestProject_VisualStudio2012And_NETFramework4AndSilverlight5()
        {
            this.AddingTheCUITeNuGetPackageToACodedUITestProject("Visual Studio 2012 and .NET Framework 4 and Silverlight 5", "2012", "4.0", "CUITe.Silverlight.VS2012", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Adding the CUITe NuGet package to a Coded UI test project")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "NuGet")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Visual Studio 2012 and .NET Framework 4.5 and Silverlight 5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Description", "Visual Studio 2012 and .NET Framework 4.5 and Silverlight 5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:VisualStudioVersion", "2012")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:TargetFrameworkVersion", "4.5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NuGetPackageId", "CUITe.Silverlight.VS2012")]
        public virtual void AddingTheCUITeNuGetPackageToACodedUITestProject_VisualStudio2012And_NETFramework4_5AndSilverlight5()
        {
            this.AddingTheCUITeNuGetPackageToACodedUITestProject("Visual Studio 2012 and .NET Framework 4.5 and Silverlight 5", "2012", "4.5", "CUITe.Silverlight.VS2012", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Adding the CUITe NuGet package to a Coded UI test project")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "NuGet")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Visual Studio 2012 and .NET Framework 4.5.1 and Silverlight 5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Description", "Visual Studio 2012 and .NET Framework 4.5.1 and Silverlight 5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:VisualStudioVersion", "2012")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:TargetFrameworkVersion", "4.5.1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NuGetPackageId", "CUITe.Silverlight.VS2012")]
        public virtual void AddingTheCUITeNuGetPackageToACodedUITestProject_VisualStudio2012And_NETFramework4_5_1AndSilverlight5()
        {
            this.AddingTheCUITeNuGetPackageToACodedUITestProject("Visual Studio 2012 and .NET Framework 4.5.1 and Silverlight 5", "2012", "4.5.1", "CUITe.Silverlight.VS2012", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Adding the CUITe NuGet package to a Coded UI test project")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "NuGet")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Visual Studio 2012 and .NET Framework 4.5.2 and Silverlight 5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Description", "Visual Studio 2012 and .NET Framework 4.5.2 and Silverlight 5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:VisualStudioVersion", "2012")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:TargetFrameworkVersion", "4.5.2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NuGetPackageId", "CUITe.Silverlight.VS2012")]
        public virtual void AddingTheCUITeNuGetPackageToACodedUITestProject_VisualStudio2012And_NETFramework4_5_2AndSilverlight5()
        {
            this.AddingTheCUITeNuGetPackageToACodedUITestProject("Visual Studio 2012 and .NET Framework 4.5.2 and Silverlight 5", "2012", "4.5.2", "CUITe.Silverlight.VS2012", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Adding the CUITe NuGet package to a Coded UI test project")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "NuGet")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Visual Studio 2012 and .NET Framework 4.6 and Silverlight 5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Description", "Visual Studio 2012 and .NET Framework 4.6 and Silverlight 5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:VisualStudioVersion", "2012")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:TargetFrameworkVersion", "4.6")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NuGetPackageId", "CUITe.Silverlight.VS2012")]
        public virtual void AddingTheCUITeNuGetPackageToACodedUITestProject_VisualStudio2012And_NETFramework4_6AndSilverlight5()
        {
            this.AddingTheCUITeNuGetPackageToACodedUITestProject("Visual Studio 2012 and .NET Framework 4.6 and Silverlight 5", "2012", "4.6", "CUITe.Silverlight.VS2012", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Adding the CUITe NuGet package to a Coded UI test project")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "NuGet")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Visual Studio 2013 and .NET Framework 4")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Description", "Visual Studio 2013 and .NET Framework 4")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:VisualStudioVersion", "2013")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:TargetFrameworkVersion", "4.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NuGetPackageId", "CUITe.VS2013")]
        public virtual void AddingTheCUITeNuGetPackageToACodedUITestProject_VisualStudio2013And_NETFramework4()
        {
            this.AddingTheCUITeNuGetPackageToACodedUITestProject("Visual Studio 2013 and .NET Framework 4", "2013", "4.0", "CUITe.VS2013", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Adding the CUITe NuGet package to a Coded UI test project")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "NuGet")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Visual Studio 2013 and .NET Framework 4.5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Description", "Visual Studio 2013 and .NET Framework 4.5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:VisualStudioVersion", "2013")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:TargetFrameworkVersion", "4.5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NuGetPackageId", "CUITe.VS2013")]
        public virtual void AddingTheCUITeNuGetPackageToACodedUITestProject_VisualStudio2013And_NETFramework4_5()
        {
            this.AddingTheCUITeNuGetPackageToACodedUITestProject("Visual Studio 2013 and .NET Framework 4.5", "2013", "4.5", "CUITe.VS2013", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Adding the CUITe NuGet package to a Coded UI test project")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "NuGet")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Visual Studio 2013 and .NET Framework 4.5.1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Description", "Visual Studio 2013 and .NET Framework 4.5.1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:VisualStudioVersion", "2013")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:TargetFrameworkVersion", "4.5.1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NuGetPackageId", "CUITe.VS2013")]
        public virtual void AddingTheCUITeNuGetPackageToACodedUITestProject_VisualStudio2013And_NETFramework4_5_1()
        {
            this.AddingTheCUITeNuGetPackageToACodedUITestProject("Visual Studio 2013 and .NET Framework 4.5.1", "2013", "4.5.1", "CUITe.VS2013", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Adding the CUITe NuGet package to a Coded UI test project")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "NuGet")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Visual Studio 2013 and .NET Framework 4.5.2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Description", "Visual Studio 2013 and .NET Framework 4.5.2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:VisualStudioVersion", "2013")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:TargetFrameworkVersion", "4.5.2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NuGetPackageId", "CUITe.VS2013")]
        public virtual void AddingTheCUITeNuGetPackageToACodedUITestProject_VisualStudio2013And_NETFramework4_5_2()
        {
            this.AddingTheCUITeNuGetPackageToACodedUITestProject("Visual Studio 2013 and .NET Framework 4.5.2", "2013", "4.5.2", "CUITe.VS2013", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Adding the CUITe NuGet package to a Coded UI test project")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "NuGet")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Visual Studio 2013 and .NET Framework 4.6")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Description", "Visual Studio 2013 and .NET Framework 4.6")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:VisualStudioVersion", "2013")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:TargetFrameworkVersion", "4.6")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NuGetPackageId", "CUITe.VS2013")]
        public virtual void AddingTheCUITeNuGetPackageToACodedUITestProject_VisualStudio2013And_NETFramework4_6()
        {
            this.AddingTheCUITeNuGetPackageToACodedUITestProject("Visual Studio 2013 and .NET Framework 4.6", "2013", "4.6", "CUITe.VS2013", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Adding the CUITe NuGet package to a Coded UI test project")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "NuGet")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Visual Studio 2013 and .NET Framework 4 and Silverlight 5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Description", "Visual Studio 2013 and .NET Framework 4 and Silverlight 5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:VisualStudioVersion", "2013")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:TargetFrameworkVersion", "4.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NuGetPackageId", "CUITe.Silverlight.VS2013")]
        public virtual void AddingTheCUITeNuGetPackageToACodedUITestProject_VisualStudio2013And_NETFramework4AndSilverlight5()
        {
            this.AddingTheCUITeNuGetPackageToACodedUITestProject("Visual Studio 2013 and .NET Framework 4 and Silverlight 5", "2013", "4.0", "CUITe.Silverlight.VS2013", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Adding the CUITe NuGet package to a Coded UI test project")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "NuGet")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Visual Studio 2013 and .NET Framework 4.5 and Silverlight 5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Description", "Visual Studio 2013 and .NET Framework 4.5 and Silverlight 5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:VisualStudioVersion", "2013")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:TargetFrameworkVersion", "4.5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NuGetPackageId", "CUITe.Silverlight.VS2013")]
        public virtual void AddingTheCUITeNuGetPackageToACodedUITestProject_VisualStudio2013And_NETFramework4_5AndSilverlight5()
        {
            this.AddingTheCUITeNuGetPackageToACodedUITestProject("Visual Studio 2013 and .NET Framework 4.5 and Silverlight 5", "2013", "4.5", "CUITe.Silverlight.VS2013", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Adding the CUITe NuGet package to a Coded UI test project")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "NuGet")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Visual Studio 2013 and .NET Framework 4.5.1 and Silverlight 5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Description", "Visual Studio 2013 and .NET Framework 4.5.1 and Silverlight 5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:VisualStudioVersion", "2013")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:TargetFrameworkVersion", "4.5.1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NuGetPackageId", "CUITe.Silverlight.VS2013")]
        public virtual void AddingTheCUITeNuGetPackageToACodedUITestProject_VisualStudio2013And_NETFramework4_5_1AndSilverlight5()
        {
            this.AddingTheCUITeNuGetPackageToACodedUITestProject("Visual Studio 2013 and .NET Framework 4.5.1 and Silverlight 5", "2013", "4.5.1", "CUITe.Silverlight.VS2013", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Adding the CUITe NuGet package to a Coded UI test project")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "NuGet")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Visual Studio 2013 and .NET Framework 4.5.2 and Silverlight 5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Description", "Visual Studio 2013 and .NET Framework 4.5.2 and Silverlight 5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:VisualStudioVersion", "2013")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:TargetFrameworkVersion", "4.5.3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NuGetPackageId", "CUITe.Silverlight.VS2013")]
        public virtual void AddingTheCUITeNuGetPackageToACodedUITestProject_VisualStudio2013And_NETFramework4_5_2AndSilverlight5()
        {
            this.AddingTheCUITeNuGetPackageToACodedUITestProject("Visual Studio 2013 and .NET Framework 4.5.2 and Silverlight 5", "2013", "4.5.3", "CUITe.Silverlight.VS2013", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Adding the CUITe NuGet package to a Coded UI test project")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "NuGet")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Visual Studio 2013 and .NET Framework 4.6 and Silverlight 5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Description", "Visual Studio 2013 and .NET Framework 4.6 and Silverlight 5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:VisualStudioVersion", "2013")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:TargetFrameworkVersion", "4.6")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NuGetPackageId", "CUITe.Silverlight.VS2013")]
        public virtual void AddingTheCUITeNuGetPackageToACodedUITestProject_VisualStudio2013And_NETFramework4_6AndSilverlight5()
        {
            this.AddingTheCUITeNuGetPackageToACodedUITestProject("Visual Studio 2013 and .NET Framework 4.6 and Silverlight 5", "2013", "4.6", "CUITe.Silverlight.VS2013", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Adding the CUITe NuGet package to a Coded UI test project")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "NuGet")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Visual Studio 2015 and .NET Framework 4")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Description", "Visual Studio 2015 and .NET Framework 4")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:VisualStudioVersion", "2015")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:TargetFrameworkVersion", "4.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NuGetPackageId", "CUITe.VS2015")]
        public virtual void AddingTheCUITeNuGetPackageToACodedUITestProject_VisualStudio2015And_NETFramework4()
        {
            this.AddingTheCUITeNuGetPackageToACodedUITestProject("Visual Studio 2015 and .NET Framework 4", "2015", "4.0", "CUITe.VS2015", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Adding the CUITe NuGet package to a Coded UI test project")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "NuGet")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Visual Studio 2015 and .NET Framework 4.5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Description", "Visual Studio 2015 and .NET Framework 4.5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:VisualStudioVersion", "2015")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:TargetFrameworkVersion", "4.5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NuGetPackageId", "CUITe.VS2015")]
        public virtual void AddingTheCUITeNuGetPackageToACodedUITestProject_VisualStudio2015And_NETFramework4_5()
        {
            this.AddingTheCUITeNuGetPackageToACodedUITestProject("Visual Studio 2015 and .NET Framework 4.5", "2015", "4.5", "CUITe.VS2015", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Adding the CUITe NuGet package to a Coded UI test project")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "NuGet")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Visual Studio 2015 and .NET Framework 4.5.1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Description", "Visual Studio 2015 and .NET Framework 4.5.1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:VisualStudioVersion", "2015")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:TargetFrameworkVersion", "4.5.1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NuGetPackageId", "CUITe.VS2015")]
        public virtual void AddingTheCUITeNuGetPackageToACodedUITestProject_VisualStudio2015And_NETFramework4_5_1()
        {
            this.AddingTheCUITeNuGetPackageToACodedUITestProject("Visual Studio 2015 and .NET Framework 4.5.1", "2015", "4.5.1", "CUITe.VS2015", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Adding the CUITe NuGet package to a Coded UI test project")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "NuGet")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Visual Studio 2015 and .NET Framework 4.5.2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Description", "Visual Studio 2015 and .NET Framework 4.5.2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:VisualStudioVersion", "2015")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:TargetFrameworkVersion", "4.5.2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NuGetPackageId", "CUITe.VS2015")]
        public virtual void AddingTheCUITeNuGetPackageToACodedUITestProject_VisualStudio2015And_NETFramework4_5_2()
        {
            this.AddingTheCUITeNuGetPackageToACodedUITestProject("Visual Studio 2015 and .NET Framework 4.5.2", "2015", "4.5.2", "CUITe.VS2015", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Adding the CUITe NuGet package to a Coded UI test project")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "NuGet")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Visual Studio 2015 and .NET Framework 4.6")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Description", "Visual Studio 2015 and .NET Framework 4.6")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:VisualStudioVersion", "2015")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:TargetFrameworkVersion", "4.6")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NuGetPackageId", "CUITe.VS2015")]
        public virtual void AddingTheCUITeNuGetPackageToACodedUITestProject_VisualStudio2015And_NETFramework4_6()
        {
            this.AddingTheCUITeNuGetPackageToACodedUITestProject("Visual Studio 2015 and .NET Framework 4.6", "2015", "4.6", "CUITe.VS2015", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Adding the CUITe NuGet package to a Coded UI test project")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "NuGet")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Visual Studio 2015 and .NET Framework 4 and Silverlight 5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Description", "Visual Studio 2015 and .NET Framework 4 and Silverlight 5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:VisualStudioVersion", "2015")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:TargetFrameworkVersion", "4.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NuGetPackageId", "CUITe.Silverlight.VS2015")]
        public virtual void AddingTheCUITeNuGetPackageToACodedUITestProject_VisualStudio2015And_NETFramework4AndSilverlight5()
        {
            this.AddingTheCUITeNuGetPackageToACodedUITestProject("Visual Studio 2015 and .NET Framework 4 and Silverlight 5", "2015", "4.0", "CUITe.Silverlight.VS2015", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Adding the CUITe NuGet package to a Coded UI test project")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "NuGet")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Visual Studio 2015 and .NET Framework 4.5 and Silverlight 5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Description", "Visual Studio 2015 and .NET Framework 4.5 and Silverlight 5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:VisualStudioVersion", "2015")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:TargetFrameworkVersion", "4.5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NuGetPackageId", "CUITe.Silverlight.VS2015")]
        public virtual void AddingTheCUITeNuGetPackageToACodedUITestProject_VisualStudio2015And_NETFramework4_5AndSilverlight5()
        {
            this.AddingTheCUITeNuGetPackageToACodedUITestProject("Visual Studio 2015 and .NET Framework 4.5 and Silverlight 5", "2015", "4.5", "CUITe.Silverlight.VS2015", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Adding the CUITe NuGet package to a Coded UI test project")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "NuGet")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Visual Studio 2015 and .NET Framework 4.5.1 and Silverlight 5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Description", "Visual Studio 2015 and .NET Framework 4.5.1 and Silverlight 5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:VisualStudioVersion", "2015")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:TargetFrameworkVersion", "4.5.1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NuGetPackageId", "CUITe.Silverlight.VS2015")]
        public virtual void AddingTheCUITeNuGetPackageToACodedUITestProject_VisualStudio2015And_NETFramework4_5_1AndSilverlight5()
        {
            this.AddingTheCUITeNuGetPackageToACodedUITestProject("Visual Studio 2015 and .NET Framework 4.5.1 and Silverlight 5", "2015", "4.5.1", "CUITe.Silverlight.VS2015", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Adding the CUITe NuGet package to a Coded UI test project")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "NuGet")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Visual Studio 2015 and .NET Framework 4.5.2 and Silverlight 5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Description", "Visual Studio 2015 and .NET Framework 4.5.2 and Silverlight 5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:VisualStudioVersion", "2015")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:TargetFrameworkVersion", "4.5.2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NuGetPackageId", "CUITe.Silverlight.VS2015")]
        public virtual void AddingTheCUITeNuGetPackageToACodedUITestProject_VisualStudio2015And_NETFramework4_5_2AndSilverlight5()
        {
            this.AddingTheCUITeNuGetPackageToACodedUITestProject("Visual Studio 2015 and .NET Framework 4.5.2 and Silverlight 5", "2015", "4.5.2", "CUITe.Silverlight.VS2015", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Adding the CUITe NuGet package to a Coded UI test project")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "NuGet")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Visual Studio 2015 and .NET Framework 4.6 and Silverlight 5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Description", "Visual Studio 2015 and .NET Framework 4.6 and Silverlight 5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:VisualStudioVersion", "2015")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:TargetFrameworkVersion", "4.6")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NuGetPackageId", "CUITe.Silverlight.VS2015")]
        public virtual void AddingTheCUITeNuGetPackageToACodedUITestProject_VisualStudio2015And_NETFramework4_6AndSilverlight5()
        {
            this.AddingTheCUITeNuGetPackageToACodedUITestProject("Visual Studio 2015 and .NET Framework 4.6 and Silverlight 5", "2015", "4.6", "CUITe.Silverlight.VS2015", ((string[])(null)));
        }
    }
}
#pragma warning restore
#endregion
