<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <VisualStudioVersion Condition="'$(VisualStudioVersion)' == ''">10.0</VisualStudioVersion>
    <TargetFramework Condition="'$(VisualStudioVersion)' == ''">net40</TargetFramework>
    <TargetFramework Condition="'$(VisualStudioVersion)' == '10.0'">net40</TargetFramework>
    <TargetFramework Condition="'$(VisualStudioVersion)' == '17.0'">net472</TargetFramework>
    <TargetFramework Condition="'$(VisualStudioVersion)' == '18.0'">net472</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>Sut.Wpf.ScreenObjects</RootNamespace>
    <AssemblyName>Sut.Wpf.ScreenObjects</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <LangVersion>7.3</LangVersion>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <ApplicationIcon>App.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\CommonAssemblyInfo.cs">
      <Link>Properties\CommonAssemblyInfo.cs</Link>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <Resource Include="App.ico" />
  </ItemGroup>
</Project>
