<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <VisualStudioVersion Condition="'$(VisualStudioVersion)' == ''">10.0</VisualStudioVersion>
    <TargetFramework Condition="'$(VisualStudioVersion)' == ''">net40</TargetFramework>
    <TargetFramework Condition="'$(VisualStudioVersion)' == '10.0'">net40</TargetFramework>
    <TargetFramework Condition="'$(VisualStudioVersion)' == '12.0'">net45</TargetFramework>
    <TargetFramework Condition="'$(VisualStudioVersion)' == '17.0'">net472</TargetFramework>
    <TargetFramework Condition="'$(VisualStudioVersion)' == '18.0'">net472</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>Sut.Silverlight.PageObjectsTest</RootNamespace>
    <AssemblyName>Sut.Silverlight.PageObjectsTest</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <LangVersion>7.3</LangVersion>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <IsCodedUITest>True</IsCodedUITest>
    <TestProjectType>CodedUITest</TestProjectType>
  </PropertyGroup>
  <Import Project="..\..\Project.props" />
  <ItemGroup>
    <Reference Include="System.Web" />
    <Reference Include="WindowsBase" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CassiniDev" Version="4.0" />
  </ItemGroup>
  <ItemGroup>
    <COMReference Include="SHDocVw">
      <Guid>{EAB22AC0-30C1-11CF-A7EB-0000C05BAE0B}</Guid>
      <VersionMajor>1</VersionMajor>
      <VersionMinor>1</VersionMinor>
      <Lcid>0</Lcid>
      <WrapperTool>tlbimp</WrapperTool>
      <Isolated>False</Isolated>
      <EmbedInteropTypes>True</EmbedInteropTypes>
    </COMReference>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\..\CommonAssemblyInfo.cs">
      <Link>Properties\CommonAssemblyInfo.cs</Link>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\CUITe.Silverlight\CUITe.Silverlight.csproj" />
    <ProjectReference Include="..\..\CUITe\CUITe.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\Sut.Silverlight.PageObjects\Bin\$(Configuration)\Sut.Silverlight.PageObjects.xap">
      <Link>Sut.Silverlight.PageObjects.xap</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Sut.Silverlight.PageObjects.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <Import Project="$(SolutionDir)\Targets\CodedUITests.targets" />
  <Import Project="$(SolutionDir)\Targets\MSTest.targets" />
  <Import Project="$(SolutionDir)\Targets\CUIT.Silverlight.targets" />
</Project>
