<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <VisualStudioVersion Condition="'$(VisualStudioVersion)' == ''">10.0</VisualStudioVersion>
    <TargetFramework Condition="'$(VisualStudioVersion)' == ''">net40</TargetFramework>
    <TargetFramework Condition="'$(VisualStudioVersion)' == '10.0'">net40</TargetFramework>
    <TargetFramework Condition="'$(VisualStudioVersion)' == '17.0'">net472</TargetFramework>
    <TargetFramework Condition="'$(VisualStudioVersion)' == '18.0'">net472</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>TestHelpers</RootNamespace>
    <AssemblyName>TestHelpers</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <LangVersion>7.3</LangVersion>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\..\CUITe.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\CommonAssemblyInfo.cs">
      <Link>Properties\CommonAssemblyInfo.cs</Link>
    </Compile>
  </ItemGroup>
</Project>
