<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <VisualStudioVersion Condition="'$(VisualStudioVersion)' == ''">10.0</VisualStudioVersion>
    <TargetFramework Condition="'$(VisualStudioVersion)' == ''">net40</TargetFramework>
    <TargetFramework Condition="'$(VisualStudioVersion)' == '10.0'">net40</TargetFramework>
    <TargetFramework Condition="'$(VisualStudioVersion)' == '17.0'">net472</TargetFramework>
    <TargetFramework Condition="'$(VisualStudioVersion)' == '18.0'">net472</TargetFramework>
    <OutputType>Library</OutputType>
    <RestorePackages>true</RestorePackages>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <Import Project="..\Project.props" />
  <PropertyGroup>
    <SignAssembly>true</SignAssembly>
  </PropertyGroup>
  <PropertyGroup>
    <AssemblyOriginatorKeyFile>..\CUITe.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="UIAutomationClient" />
    <Reference Include="UIAutomationTypes" />
    <Reference Include="WindowsBase" />
  </ItemGroup>
  <ItemGroup>
    <COMReference Include="SHDocVw">
      <Guid>{EAB22AC0-30C1-11CF-A7EB-0000C05BAE0B}</Guid>
      <VersionMajor>1</VersionMajor>
      <VersionMinor>1</VersionMinor>
      <Lcid>0</Lcid>
      <WrapperTool>tlbimp</WrapperTool>
      <Isolated>False</Isolated>
      <EmbedInteropTypes>True</EmbedInteropTypes>
    </COMReference>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\CommonAssemblyInfo.cs">
      <Link>Properties\CommonAssemblyInfo.cs</Link>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.TestPlatform" Version="17.13.0" GeneratePathProperty="true" />
    <PackageReference Include="Unofficial.Microsoft.mshtml" Version="7.0.3300" />
  </ItemGroup>
  <Import Project="$(SolutionDir)\Targets\CUIT.targets" />
</Project>